/**
 * Permission Constants
 * Defines all permissions for RBAC system
 * Based on NEW-PLANS.md requirements
 */

// Resource types
export const RESOURCES = {
  PATIENT: 'patient',
  APPOINTMENT: 'appointment',
  PRESCRIPTION: 'prescription',
  INVOICE: 'invoice',
  PAYMENT: 'payment',
  LAB_TEST: 'lab_test',
  LAB_ORDER: 'lab_order',
  LAB_RESULT: 'lab_result',
  CLINICAL_NOTE: 'clinical_note',
  INVENTORY: 'inventory',
  USER: 'user',
  DOCTOR: 'doctor',
  DEPARTMENT: 'department',
  REPORT: 'report',
  SETTINGS: 'settings',
  AUDIT_LOG: 'audit_log',
  SUBSCRIPTION: 'subscription',
  NOTIFICATION: 'notification',
  TELEMEDICINE: 'telemedicine',
  QUEUE: 'queue',
};

// Action types
export const ACTIONS = {
  CREATE: 'create',
  READ: 'read',
  UPDATE: 'update',
  DELETE: 'delete',
  EXPORT: 'export',
  MANAGE: 'manage', // Full access
  APPROVE: 'approve',
  VERIFY: 'verify',
  CANCEL: 'cancel',
  ASSIGN: 'assign',
};

/**
 * Permission matrix: Role -> Resource -> Actions
 * Based on NEW-PLANS.md role definitions
 */
export const PERMISSIONS = {
  // Super Admin - Full access to everything
  super_admin: {
    [RESOURCES.PATIENT]: [ACTIONS.MANAGE],
    [RESOURCES.APPOINTMENT]: [ACTIONS.MANAGE],
    [RESOURCES.PRESCRIPTION]: [ACTIONS.MANAGE],
    [RESOURCES.INVOICE]: [ACTIONS.MANAGE],
    [RESOURCES.PAYMENT]: [ACTIONS.MANAGE],
    [RESOURCES.LAB_TEST]: [ACTIONS.MANAGE],
    [RESOURCES.LAB_ORDER]: [ACTIONS.MANAGE],
    [RESOURCES.LAB_RESULT]: [ACTIONS.MANAGE],
    [RESOURCES.CLINICAL_NOTE]: [ACTIONS.MANAGE],
    [RESOURCES.INVENTORY]: [ACTIONS.MANAGE],
    [RESOURCES.USER]: [ACTIONS.MANAGE],
    [RESOURCES.DOCTOR]: [ACTIONS.MANAGE],
    [RESOURCES.DEPARTMENT]: [ACTIONS.MANAGE],
    [RESOURCES.REPORT]: [ACTIONS.MANAGE],
    [RESOURCES.SETTINGS]: [ACTIONS.MANAGE],
    [RESOURCES.AUDIT_LOG]: [ACTIONS.MANAGE],
    [RESOURCES.SUBSCRIPTION]: [ACTIONS.MANAGE],
    [RESOURCES.NOTIFICATION]: [ACTIONS.MANAGE],
    [RESOURCES.TELEMEDICINE]: [ACTIONS.MANAGE],
  },

  // Clinic Admin - Full access within their clinic
  clinic_admin: {
    [RESOURCES.PATIENT]: [ACTIONS.MANAGE],
    [RESOURCES.APPOINTMENT]: [ACTIONS.MANAGE],
    [RESOURCES.PRESCRIPTION]: [ACTIONS.MANAGE],
    [RESOURCES.INVOICE]: [ACTIONS.MANAGE],
    [RESOURCES.PAYMENT]: [ACTIONS.MANAGE],
    [RESOURCES.LAB_TEST]: [ACTIONS.MANAGE],
    [RESOURCES.LAB_ORDER]: [ACTIONS.MANAGE],
    [RESOURCES.LAB_RESULT]: [ACTIONS.MANAGE],
    [RESOURCES.CLINICAL_NOTE]: [ACTIONS.MANAGE],
    [RESOURCES.INVENTORY]: [ACTIONS.MANAGE],
    [RESOURCES.USER]: [ACTIONS.MANAGE],
    [RESOURCES.DOCTOR]: [ACTIONS.MANAGE],
    [RESOURCES.DEPARTMENT]: [ACTIONS.MANAGE],
    [RESOURCES.REPORT]: [ACTIONS.MANAGE],
    [RESOURCES.SETTINGS]: [ACTIONS.MANAGE],
    [RESOURCES.AUDIT_LOG]: [ACTIONS.READ],
    [RESOURCES.SUBSCRIPTION]: [ACTIONS.READ],
    [RESOURCES.NOTIFICATION]: [ACTIONS.MANAGE],
    [RESOURCES.TELEMEDICINE]: [ACTIONS.MANAGE],
    [RESOURCES.QUEUE]: [ACTIONS.MANAGE],
  },

  // Doctor - Clinical operations
  doctor: {
    [RESOURCES.PATIENT]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.APPOINTMENT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.CANCEL],
    [RESOURCES.PRESCRIPTION]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.INVOICE]: [ACTIONS.READ],
    [RESOURCES.PAYMENT]: [ACTIONS.READ],
    [RESOURCES.LAB_TEST]: [ACTIONS.READ],
    [RESOURCES.LAB_ORDER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.LAB_RESULT]: [ACTIONS.READ, ACTIONS.VERIFY],
    [RESOURCES.CLINICAL_NOTE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.INVENTORY]: [ACTIONS.READ],
    [RESOURCES.USER]: [ACTIONS.READ],
    [RESOURCES.DOCTOR]: [ACTIONS.READ, ACTIONS.UPDATE], // Own profile
    [RESOURCES.DEPARTMENT]: [ACTIONS.READ],
    [RESOURCES.REPORT]: [ACTIONS.READ],
    [RESOURCES.SETTINGS]: [ACTIONS.READ],
    [RESOURCES.AUDIT_LOG]: [], // No access
    [RESOURCES.SUBSCRIPTION]: [], // No access
    [RESOURCES.NOTIFICATION]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.TELEMEDICINE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.QUEUE]: [ACTIONS.READ, ACTIONS.UPDATE],
  },

  // Nurse - Clinical support
  nurse: {
    [RESOURCES.PATIENT]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.APPOINTMENT]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.PRESCRIPTION]: [ACTIONS.READ],
    [RESOURCES.INVOICE]: [ACTIONS.READ],
    [RESOURCES.PAYMENT]: [ACTIONS.READ],
    [RESOURCES.LAB_TEST]: [ACTIONS.READ],
    [RESOURCES.LAB_ORDER]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.LAB_RESULT]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.CLINICAL_NOTE]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.INVENTORY]: [ACTIONS.READ],
    [RESOURCES.USER]: [ACTIONS.READ],
    [RESOURCES.DOCTOR]: [ACTIONS.READ],
    [RESOURCES.DEPARTMENT]: [ACTIONS.READ],
    [RESOURCES.REPORT]: [ACTIONS.READ],
    [RESOURCES.SETTINGS]: [ACTIONS.READ],
    [RESOURCES.AUDIT_LOG]: [],
    [RESOURCES.SUBSCRIPTION]: [],
    [RESOURCES.NOTIFICATION]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.TELEMEDICINE]: [ACTIONS.READ],
  },

  // Receptionist - Front desk operations
  receptionist: {
    [RESOURCES.PATIENT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.APPOINTMENT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.CANCEL],
    [RESOURCES.PRESCRIPTION]: [ACTIONS.READ],
    [RESOURCES.INVOICE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.PAYMENT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.LAB_TEST]: [ACTIONS.READ],
    [RESOURCES.LAB_ORDER]: [ACTIONS.READ],
    [RESOURCES.LAB_RESULT]: [ACTIONS.READ],
    [RESOURCES.CLINICAL_NOTE]: [ACTIONS.READ],
    [RESOURCES.INVENTORY]: [ACTIONS.READ],
    [RESOURCES.USER]: [ACTIONS.READ],
    [RESOURCES.DOCTOR]: [ACTIONS.READ],
    [RESOURCES.DEPARTMENT]: [ACTIONS.READ],
    [RESOURCES.REPORT]: [ACTIONS.READ],
    [RESOURCES.SETTINGS]: [ACTIONS.READ],
    [RESOURCES.AUDIT_LOG]: [],
    [RESOURCES.SUBSCRIPTION]: [],
    [RESOURCES.NOTIFICATION]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.TELEMEDICINE]: [ACTIONS.READ],
    [RESOURCES.QUEUE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
  },

  // Accountant - Financial operations
  accountant: {
    [RESOURCES.PATIENT]: [ACTIONS.READ],
    [RESOURCES.APPOINTMENT]: [ACTIONS.READ],
    [RESOURCES.PRESCRIPTION]: [ACTIONS.READ],
    [RESOURCES.INVOICE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.PAYMENT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.LAB_TEST]: [ACTIONS.READ],
    [RESOURCES.LAB_ORDER]: [ACTIONS.READ],
    [RESOURCES.LAB_RESULT]: [ACTIONS.READ],
    [RESOURCES.CLINICAL_NOTE]: [ACTIONS.READ],
    [RESOURCES.INVENTORY]: [ACTIONS.READ],
    [RESOURCES.USER]: [ACTIONS.READ],
    [RESOURCES.DOCTOR]: [ACTIONS.READ],
    [RESOURCES.DEPARTMENT]: [ACTIONS.READ],
    [RESOURCES.REPORT]: [ACTIONS.READ, ACTIONS.EXPORT],
    [RESOURCES.SETTINGS]: [ACTIONS.READ],
    [RESOURCES.AUDIT_LOG]: [],
    [RESOURCES.SUBSCRIPTION]: [ACTIONS.READ],
    [RESOURCES.NOTIFICATION]: [ACTIONS.READ],
    [RESOURCES.TELEMEDICINE]: [],
  },

  // Patient - Portal access (own data only)
  patient: {
    [RESOURCES.PATIENT]: [ACTIONS.READ, ACTIONS.UPDATE], // Own profile only
    [RESOURCES.APPOINTMENT]: [ACTIONS.CREATE, ACTIONS.READ], // Book and view own appointments
    [RESOURCES.PRESCRIPTION]: [ACTIONS.READ], // View own prescriptions
    [RESOURCES.INVOICE]: [ACTIONS.READ], // View own invoices
    [RESOURCES.PAYMENT]: [ACTIONS.READ], // View own payments
    [RESOURCES.LAB_RESULT]: [ACTIONS.READ], // View own lab results
    [RESOURCES.CLINICAL_NOTE]: [ACTIONS.READ], // View own clinical notes
    [RESOURCES.USER]: [],
    [RESOURCES.DOCTOR]: [ACTIONS.READ], // View doctor profiles
    [RESOURCES.DEPARTMENT]: [ACTIONS.READ],
    [RESOURCES.REPORT]: [],
    [RESOURCES.SETTINGS]: [],
    [RESOURCES.AUDIT_LOG]: [],
    [RESOURCES.SUBSCRIPTION]: [],
    [RESOURCES.NOTIFICATION]: [ACTIONS.READ, ACTIONS.UPDATE], // Own notifications
    [RESOURCES.TELEMEDICINE]: [ACTIONS.READ], // Own telemedicine sessions
    [RESOURCES.QUEUE]: [ACTIONS.READ], // View own queue position
  },

  // Pharmacist - Pharmacy operations
  pharmacist: {
    [RESOURCES.PATIENT]: [ACTIONS.READ],
    [RESOURCES.APPOINTMENT]: [ACTIONS.READ],
    [RESOURCES.PRESCRIPTION]: [ACTIONS.READ, ACTIONS.UPDATE], // Dispense
    [RESOURCES.INVOICE]: [ACTIONS.READ],
    [RESOURCES.PAYMENT]: [ACTIONS.READ],
    [RESOURCES.LAB_TEST]: [ACTIONS.READ],
    [RESOURCES.LAB_ORDER]: [ACTIONS.READ],
    [RESOURCES.LAB_RESULT]: [ACTIONS.READ],
    [RESOURCES.CLINICAL_NOTE]: [ACTIONS.READ],
    [RESOURCES.INVENTORY]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.USER]: [ACTIONS.READ],
    [RESOURCES.DOCTOR]: [ACTIONS.READ],
    [RESOURCES.DEPARTMENT]: [ACTIONS.READ],
    [RESOURCES.REPORT]: [ACTIONS.READ],
    [RESOURCES.SETTINGS]: [ACTIONS.READ],
    [RESOURCES.AUDIT_LOG]: [],
    [RESOURCES.SUBSCRIPTION]: [],
    [RESOURCES.NOTIFICATION]: [ACTIONS.READ],
    [RESOURCES.TELEMEDICINE]: [],
    [RESOURCES.QUEUE]: [ACTIONS.READ],
  },

  // Manager - External manager with limited access
  manager: {
    [RESOURCES.PATIENT]: [ACTIONS.READ],
    [RESOURCES.APPOINTMENT]: [ACTIONS.READ],
    [RESOURCES.PRESCRIPTION]: [ACTIONS.READ],
    [RESOURCES.INVOICE]: [ACTIONS.READ],
    [RESOURCES.PAYMENT]: [ACTIONS.READ],
    [RESOURCES.LAB_TEST]: [ACTIONS.READ],
    [RESOURCES.LAB_ORDER]: [ACTIONS.READ],
    [RESOURCES.LAB_RESULT]: [ACTIONS.READ],
    [RESOURCES.CLINICAL_NOTE]: [ACTIONS.READ],
    [RESOURCES.INVENTORY]: [ACTIONS.READ],
    [RESOURCES.USER]: [ACTIONS.READ],
    [RESOURCES.DOCTOR]: [ACTIONS.READ],
    [RESOURCES.DEPARTMENT]: [ACTIONS.READ],
    [RESOURCES.REPORT]: [ACTIONS.READ, ACTIONS.EXPORT],
    [RESOURCES.SETTINGS]: [ACTIONS.READ],
    [RESOURCES.AUDIT_LOG]: [],
    [RESOURCES.SUBSCRIPTION]: [ACTIONS.READ],
    [RESOURCES.NOTIFICATION]: [ACTIONS.READ],
    [RESOURCES.TELEMEDICINE]: [],
    [RESOURCES.QUEUE]: [ACTIONS.READ],
  },
};

/**
 * Check if a role has permission for a resource and action
 */
export function hasPermission(role, resource, action) {
  if (!PERMISSIONS[role]) {
    return false;
  }

  const rolePermissions = PERMISSIONS[role];
  if (!rolePermissions[resource]) {
    return false;
  }

  const allowedActions = rolePermissions[resource];
  
  // MANAGE permission grants all actions
  if (allowedActions.includes(ACTIONS.MANAGE)) {
    return true;
  }

  return allowedActions.includes(action);
}

/**
 * Get all permissions for a role
 */
export function getRolePermissions(role) {
  return PERMISSIONS[role] || {};
}

/**
 * Get all roles that have permission for a resource and action
 */
export function getRolesWithPermission(resource, action) {
  const roles = [];
  for (const [role, permissions] of Object.entries(PERMISSIONS)) {
    if (hasPermission(role, resource, action)) {
      roles.push(role);
    }
  }
  return roles;
}
