/** @type {import('tailwindcss').Config} */
const config = {
  darkMode: 'class',
  blocklist: ['focus:ring-primary-500'],
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: '16px',
        sm: '20px',
        lg: '24px',
        xl: '28px',
        '2xl': '32px',
      },
    },
    extend: {
      colors: {
        primary: {
          900: 'var(--color-primary-900)',
          700: 'var(--color-primary-700)',
          600: 'var(--color-primary-600)',
          500: 'var(--color-primary-500)',
          400: 'var(--color-primary-400)',
          300: 'var(--color-primary-300)',
          200: 'var(--color-primary-200)',
          100: 'var(--color-primary-100)',
          50: 'var(--color-primary-50)',
        },
        secondary: {
          700: '#1E874F',
          500: '#27AE60',
          300: '#52C48F',
          100: '#E8F8EF',
        },
        neutral: {
          900: '#1A1A1A',
          700: '#4F4F4F',
          500: '#828282',
          300: '#D1D1D1',
          200: '#E6E9EE',
          100: '#F7FAFC',
          50: '#FFFFFF',
        },
        status: {
          success: '#27AE60',
          warning: '#F2C94C',
          error: '#EB5757',
          info: 'var(--color-primary)',
        },
        success: {
          700: '#1E874F',
          600: '#27AE60',
          500: '#27AE60',
          400: '#52C48F',
          300: '#52C48F',
          100: '#E8F8EF',
        },
      },
      fontFamily: {
        sans: ['var(--font-family)'],
        mono: ['var(--font-mono)'],
      },
      fontSize: {
        h1: ['var(--dashboard-h1)', { lineHeight: '1.25', fontWeight: '700' }],
        h2: ['var(--dashboard-h2)', { lineHeight: '1.25', fontWeight: '600' }],
        h3: ['var(--dashboard-h3)', { lineHeight: '1.3', fontWeight: '600' }],
        h4: ['var(--text-body-lg)', { lineHeight: '1.35', fontWeight: '600' }],
        'body-lg': [
          'var(--text-body-lg)',
          { lineHeight: 'var(--text-body-lg-line-height)', fontWeight: '400' },
        ],
        'body-md': [
          'var(--text-body-md)',
          { lineHeight: 'var(--text-body-md-line-height)', fontWeight: '400' },
        ],
        'body-sm': [
          'var(--text-body-sm)',
          { lineHeight: 'var(--text-body-sm-line-height)', fontWeight: '400' },
        ],
        'body-xs': [
          'var(--text-body-xs)',
          { lineHeight: 'var(--text-body-xs-line-height)', fontWeight: '400' },
        ],
        button: ['1rem', { lineHeight: '1.25', fontWeight: '600' }],
        'metric-lg': ['1.5rem', { lineHeight: '1.25', fontWeight: '600' }],
        'metric-md': ['1.25rem', { lineHeight: '1.3', fontWeight: '600' }],
        'metric-sm': ['1.125rem', { lineHeight: '1.35', fontWeight: '600' }],
      },
      spacing: {
        4: '4px',
        8: '8px',
        12: '12px',
        16: '16px',
        24: '24px',
        32: '32px',
        40: '40px',
        48: '48px',
        56: '56px',
        64: '64px',
        'icon-text': 'var(--icon-text-gap)',
      },
      borderRadius: {
        none: '0',
        sm: '4px',
        DEFAULT: '8px',
        md: '6px',
        lg: '8px',
        xl: '12px',
        '2xl': '16px',
        full: '9999px',
        button: '8px',
        card: '8px',
        input: '8px',
      },
      boxShadow: {
        sm: '0 1px 2px rgba(0,0,0,0.04)',
        md: '0 2px 4px rgba(0,0,0,0.06)',
        lg: '0 4px 12px rgba(0,0,0,0.08)',
        xl: '0 8px 20px rgba(0,0,0,0.12)',
        focus: '0 0 0 3px rgba(18,57,146,0.20)',
      },
    },
  },
  plugins: [],
};

module.exports = config;
