export {
  SkeletonFactory,
  SKELETON_TYPES,
  StatsCardsSkeleton,
  ChartSkeleton,
  CardSkeleton,
  ListSkeleton,
  CalendarSkeleton,
  QueueSkeleton,
  ReportTabSkeleton,
  TabContentSkeleton,
  AppointmentsListSkeleton,
  PrescriptionsListSkeleton,
  PatientsListSkeleton,
} from './SkeletonFactory';
