/**
 * Permission Constants
 * Defines all permissions for RBAC system.
 * Aligned with CursorMD/New clinic-complete-specification.md (Super Admin, Doctor, Admin, Manager).
 *
 * THREE-TIER ACCESS MODEL:
 * 1. Super Admin – Full access. No subscription or tenant; sees all system features and /admin.
 * 2. Doctor – Access as per subscription. Clinic features (nav, modules) are gated by subscription
 *    (FeatureContext.hasFeature from /api/features → tenant’s plan). Doctor creates Admin/Manager
 *    accounts and assigns their role = required access for clinic work.
 * 3. Admin / Manager – Access as per role assigned by Doctor when creating the account.
 *    Admin = full clinic access (this matrix). Manager = limited clinic access (this matrix).
 *    Only Doctor (and Super Admin) can create or assign Admin/Manager (see canAssignAdminManager).
 *    Admin and Manager can only see/use what the clinic’s subscription plan allows (same plan as
 *    Doctor); the Doctor cannot grant access to features the plan does not include.
 */

// Resource types
export const RESOURCES = {
  PATIENT: 'patient',
  APPOINTMENT: 'appointment',
  PRESCRIPTION: 'prescription',
  INVOICE: 'invoice',
  PAYMENT: 'payment',
  LAB_TEST: 'lab_test',
  LAB_ORDER: 'lab_order',
  LAB_RESULT: 'lab_result',
  CLINICAL_NOTE: 'clinical_note',
  INVENTORY: 'inventory',
  USER: 'user',
  DOCTOR: 'doctor',
  DEPARTMENT: 'department',
  REPORT: 'report',
  SETTINGS: 'settings',
  AUDIT_LOG: 'audit_log',
  SUBSCRIPTION: 'subscription',
  NOTIFICATION: 'notification',
  TELEMEDICINE: 'telemedicine',
  QUEUE: 'queue',
  IMAGING_STUDY: 'imaging_study',
  REFERRAL: 'referral',
  INSURANCE_CLAIM: 'insurance_claim',
  PROCEDURE: 'procedure',
  CARE_PLAN: 'care_plan',
  TASK: 'task',
  CONSENT: 'consent',
};

// Action types
export const ACTIONS = {
  CREATE: 'create',
  READ: 'read',
  UPDATE: 'update',
  DELETE: 'delete',
  EXPORT: 'export',
  MANAGE: 'manage', // Full access
  APPROVE: 'approve',
  VERIFY: 'verify',
  CANCEL: 'cancel',
  ASSIGN: 'assign',
};

/**
 * Permission matrix: Role -> Resource -> Actions
 * Based on NEW-PLANS.md role definitions
 *
 * Super Admin: Platform role (company side). Complimentary rights only.
 * No tenant PHI access: /admin/patients and /admin/appointments are blocked at API level.
 */
export const PERMISSIONS = {
  // Super Admin - Platform oversight only; no tenant PHI (patients, appointments blocked via API)
  super_admin: {
    [RESOURCES.PATIENT]: [ACTIONS.MANAGE],
    [RESOURCES.APPOINTMENT]: [ACTIONS.MANAGE],
    [RESOURCES.PRESCRIPTION]: [ACTIONS.MANAGE],
    [RESOURCES.INVOICE]: [ACTIONS.MANAGE],
    [RESOURCES.PAYMENT]: [ACTIONS.MANAGE],
    [RESOURCES.LAB_TEST]: [ACTIONS.MANAGE],
    [RESOURCES.LAB_ORDER]: [ACTIONS.MANAGE],
    [RESOURCES.LAB_RESULT]: [ACTIONS.MANAGE],
    [RESOURCES.CLINICAL_NOTE]: [ACTIONS.MANAGE],
    [RESOURCES.INVENTORY]: [ACTIONS.MANAGE],
    [RESOURCES.USER]: [ACTIONS.MANAGE],
    [RESOURCES.DOCTOR]: [ACTIONS.MANAGE],
    [RESOURCES.DEPARTMENT]: [ACTIONS.MANAGE],
    [RESOURCES.REPORT]: [ACTIONS.MANAGE],
    [RESOURCES.SETTINGS]: [ACTIONS.MANAGE],
    [RESOURCES.AUDIT_LOG]: [ACTIONS.MANAGE],
    [RESOURCES.SUBSCRIPTION]: [ACTIONS.MANAGE],
    [RESOURCES.NOTIFICATION]: [ACTIONS.MANAGE],
    [RESOURCES.TELEMEDICINE]: [ACTIONS.MANAGE],
    [RESOURCES.PROCEDURE]: [ACTIONS.MANAGE],
    [RESOURCES.CARE_PLAN]: [ACTIONS.MANAGE],
    [RESOURCES.TASK]: [ACTIONS.MANAGE],
    [RESOURCES.CONSENT]: [ACTIONS.MANAGE],
  },

  // Admin (CursorMD/New: full clinic ops except assign Admin/Manager; prescription view-only; no medical notes/add diagnosis)
  // clinic_admin in DB is treated as Admin in permissions (see hasPermission).
  // SUBSCRIPTION:CREATE allowed here; isPrimaryAccount in handler is the gate for who can mutate.
  admin: {
    [RESOURCES.PATIENT]: [ACTIONS.MANAGE],
    [RESOURCES.APPOINTMENT]: [ACTIONS.MANAGE],
    [RESOURCES.PRESCRIPTION]: [ACTIONS.READ], // Spec: Admin – Create prescription View Only
    [RESOURCES.INVOICE]: [ACTIONS.MANAGE],
    [RESOURCES.PAYMENT]: [ACTIONS.MANAGE],
    [RESOURCES.LAB_TEST]: [ACTIONS.MANAGE],
    [RESOURCES.LAB_ORDER]: [ACTIONS.MANAGE],
    [RESOURCES.LAB_RESULT]: [ACTIONS.MANAGE],
    [RESOURCES.CLINICAL_NOTE]: [], // Spec: Admin – Medical notes ❌
    [RESOURCES.INVENTORY]: [ACTIONS.MANAGE],
    [RESOURCES.USER]: [ACTIONS.MANAGE], // Cannot assign Admin/Manager – enforced by canAssignAdminManager
    [RESOURCES.DOCTOR]: [ACTIONS.MANAGE],
    [RESOURCES.DEPARTMENT]: [ACTIONS.MANAGE],
    [RESOURCES.REPORT]: [ACTIONS.MANAGE],
    [RESOURCES.SETTINGS]: [ACTIONS.MANAGE], // Spec: Limited – billing/profile/backup gated at API where needed
    [RESOURCES.AUDIT_LOG]: [ACTIONS.READ],
    [RESOURCES.SUBSCRIPTION]: [ACTIONS.READ, ACTIONS.CREATE],
    [RESOURCES.NOTIFICATION]: [ACTIONS.MANAGE],
    [RESOURCES.TELEMEDICINE]: [ACTIONS.MANAGE],
    [RESOURCES.QUEUE]: [ACTIONS.MANAGE],
    [RESOURCES.IMAGING_STUDY]: [ACTIONS.MANAGE],
    [RESOURCES.REFERRAL]: [ACTIONS.MANAGE],
    [RESOURCES.INSURANCE_CLAIM]: [ACTIONS.MANAGE],
    [RESOURCES.PROCEDURE]: [ACTIONS.MANAGE],
    [RESOURCES.CARE_PLAN]: [ACTIONS.READ], // Spec: Admin – Treatment plans View Only
    [RESOURCES.TASK]: [ACTIONS.MANAGE],
    [RESOURCES.CONSENT]: [ACTIONS.MANAGE],
  },

  // Clinic Admin – alias for Admin (same permission set)
  clinic_admin: {
    [RESOURCES.PATIENT]: [ACTIONS.MANAGE],
    [RESOURCES.APPOINTMENT]: [ACTIONS.MANAGE],
    [RESOURCES.PRESCRIPTION]: [ACTIONS.READ],
    [RESOURCES.INVOICE]: [ACTIONS.MANAGE],
    [RESOURCES.PAYMENT]: [ACTIONS.MANAGE],
    [RESOURCES.LAB_TEST]: [ACTIONS.MANAGE],
    [RESOURCES.LAB_ORDER]: [ACTIONS.MANAGE],
    [RESOURCES.LAB_RESULT]: [ACTIONS.MANAGE],
    [RESOURCES.CLINICAL_NOTE]: [], // Spec: Admin – Medical notes ❌
    [RESOURCES.INVENTORY]: [ACTIONS.MANAGE],
    [RESOURCES.USER]: [ACTIONS.MANAGE],
    [RESOURCES.DOCTOR]: [ACTIONS.MANAGE],
    [RESOURCES.DEPARTMENT]: [ACTIONS.MANAGE],
    [RESOURCES.REPORT]: [ACTIONS.MANAGE],
    [RESOURCES.SETTINGS]: [ACTIONS.MANAGE],
    [RESOURCES.AUDIT_LOG]: [ACTIONS.READ],
    [RESOURCES.SUBSCRIPTION]: [ACTIONS.READ, ACTIONS.CREATE],
    [RESOURCES.NOTIFICATION]: [ACTIONS.MANAGE],
    [RESOURCES.TELEMEDICINE]: [ACTIONS.MANAGE],
    [RESOURCES.QUEUE]: [ACTIONS.MANAGE],
    [RESOURCES.IMAGING_STUDY]: [ACTIONS.MANAGE],
    [RESOURCES.REFERRAL]: [ACTIONS.MANAGE],
    [RESOURCES.INSURANCE_CLAIM]: [ACTIONS.MANAGE],
    [RESOURCES.PROCEDURE]: [ACTIONS.MANAGE],
    [RESOURCES.CARE_PLAN]: [ACTIONS.READ],
    [RESOURCES.TASK]: [ACTIONS.MANAGE],
    [RESOURCES.CONSENT]: [ACTIONS.MANAGE],
  },

  // Doctor (Clinic Owner) – spec: full clinic access (dashboard, patients, appointments, billing, inventory, staff, reports, settings, prescriptions, medical notes, telemedicine)
  doctor: {
    [RESOURCES.PATIENT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.APPOINTMENT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.CANCEL],
    [RESOURCES.PRESCRIPTION]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.INVOICE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.PAYMENT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.LAB_TEST]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.LAB_ORDER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.LAB_RESULT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.VERIFY],
    [RESOURCES.CLINICAL_NOTE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.INVENTORY]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.USER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.DOCTOR]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.DEPARTMENT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.REPORT]: [ACTIONS.READ, ACTIONS.EXPORT],
    [RESOURCES.SETTINGS]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.AUDIT_LOG]: [],
    [RESOURCES.SUBSCRIPTION]: [ACTIONS.READ, ACTIONS.CREATE],
    [RESOURCES.NOTIFICATION]: [ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.MANAGE],
    [RESOURCES.TELEMEDICINE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.QUEUE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.IMAGING_STUDY]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.REFERRAL]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.INSURANCE_CLAIM]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.PROCEDURE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.CARE_PLAN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.TASK]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.CONSENT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
  },

  // Nurse - Clinical support
  nurse: {
    [RESOURCES.PATIENT]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.APPOINTMENT]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.PRESCRIPTION]: [ACTIONS.READ],
    [RESOURCES.INVOICE]: [ACTIONS.READ],
    [RESOURCES.PAYMENT]: [ACTIONS.READ],
    [RESOURCES.LAB_TEST]: [ACTIONS.READ],
    [RESOURCES.LAB_ORDER]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.LAB_RESULT]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.CLINICAL_NOTE]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.INVENTORY]: [ACTIONS.READ],
    [RESOURCES.USER]: [ACTIONS.READ],
    [RESOURCES.DOCTOR]: [ACTIONS.READ],
    [RESOURCES.DEPARTMENT]: [ACTIONS.READ],
    [RESOURCES.REPORT]: [ACTIONS.READ],
    [RESOURCES.SETTINGS]: [ACTIONS.READ],
    [RESOURCES.AUDIT_LOG]: [],
    [RESOURCES.SUBSCRIPTION]: [],
    [RESOURCES.NOTIFICATION]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.TELEMEDICINE]: [ACTIONS.READ],
    [RESOURCES.IMAGING_STUDY]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.REFERRAL]: [ACTIONS.READ],
    [RESOURCES.INSURANCE_CLAIM]: [ACTIONS.READ],
    [RESOURCES.PROCEDURE]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.CARE_PLAN]: [ACTIONS.READ],
    [RESOURCES.TASK]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.CONSENT]: [ACTIONS.READ, ACTIONS.CREATE],
  },

  // Receptionist - Front desk operations
  receptionist: {
    [RESOURCES.PATIENT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.APPOINTMENT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.CANCEL],
    [RESOURCES.PRESCRIPTION]: [ACTIONS.READ],
    [RESOURCES.INVOICE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.PAYMENT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.LAB_TEST]: [ACTIONS.READ],
    [RESOURCES.LAB_ORDER]: [ACTIONS.READ],
    [RESOURCES.LAB_RESULT]: [ACTIONS.READ],
    [RESOURCES.CLINICAL_NOTE]: [ACTIONS.READ],
    [RESOURCES.INVENTORY]: [ACTIONS.READ],
    [RESOURCES.USER]: [ACTIONS.READ],
    [RESOURCES.DOCTOR]: [ACTIONS.READ],
    [RESOURCES.DEPARTMENT]: [ACTIONS.READ],
    [RESOURCES.REPORT]: [ACTIONS.READ],
    [RESOURCES.SETTINGS]: [ACTIONS.READ],
    [RESOURCES.AUDIT_LOG]: [],
    [RESOURCES.SUBSCRIPTION]: [],
    [RESOURCES.NOTIFICATION]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.TELEMEDICINE]: [ACTIONS.READ],
    [RESOURCES.QUEUE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.IMAGING_STUDY]: [ACTIONS.READ],
    [RESOURCES.REFERRAL]: [ACTIONS.READ],
    [RESOURCES.INSURANCE_CLAIM]: [ACTIONS.READ],
    [RESOURCES.PROCEDURE]: [ACTIONS.READ],
    [RESOURCES.CARE_PLAN]: [ACTIONS.READ],
    [RESOURCES.TASK]: [ACTIONS.READ],
    [RESOURCES.CONSENT]: [ACTIONS.READ],
  },

  // Accountant - Financial operations
  accountant: {
    [RESOURCES.PATIENT]: [ACTIONS.READ],
    [RESOURCES.APPOINTMENT]: [ACTIONS.READ],
    [RESOURCES.PRESCRIPTION]: [ACTIONS.READ],
    [RESOURCES.INVOICE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.PAYMENT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.LAB_TEST]: [ACTIONS.READ],
    [RESOURCES.LAB_ORDER]: [ACTIONS.READ],
    [RESOURCES.LAB_RESULT]: [ACTIONS.READ],
    [RESOURCES.CLINICAL_NOTE]: [ACTIONS.READ],
    [RESOURCES.INVENTORY]: [ACTIONS.READ],
    [RESOURCES.USER]: [ACTIONS.READ],
    [RESOURCES.DOCTOR]: [ACTIONS.READ],
    [RESOURCES.DEPARTMENT]: [ACTIONS.READ],
    [RESOURCES.REPORT]: [ACTIONS.READ, ACTIONS.EXPORT],
    [RESOURCES.SETTINGS]: [ACTIONS.READ],
    [RESOURCES.AUDIT_LOG]: [],
    [RESOURCES.SUBSCRIPTION]: [ACTIONS.READ],
    [RESOURCES.NOTIFICATION]: [ACTIONS.READ],
    [RESOURCES.TELEMEDICINE]: [],
    [RESOURCES.PROCEDURE]: [ACTIONS.READ],
    [RESOURCES.CARE_PLAN]: [],
    [RESOURCES.TASK]: [ACTIONS.READ],
    [RESOURCES.CONSENT]: [ACTIONS.READ],
  },

  // Pharmacist - Pharmacy operations
  pharmacist: {
    [RESOURCES.PATIENT]: [ACTIONS.READ],
    [RESOURCES.APPOINTMENT]: [ACTIONS.READ],
    [RESOURCES.PRESCRIPTION]: [ACTIONS.READ, ACTIONS.UPDATE], // Dispense
    [RESOURCES.INVOICE]: [ACTIONS.READ],
    [RESOURCES.PAYMENT]: [ACTIONS.READ],
    [RESOURCES.LAB_TEST]: [ACTIONS.READ],
    [RESOURCES.LAB_ORDER]: [ACTIONS.READ],
    [RESOURCES.LAB_RESULT]: [ACTIONS.READ],
    [RESOURCES.CLINICAL_NOTE]: [ACTIONS.READ],
    [RESOURCES.INVENTORY]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.USER]: [ACTIONS.READ],
    [RESOURCES.DOCTOR]: [ACTIONS.READ],
    [RESOURCES.DEPARTMENT]: [ACTIONS.READ],
    [RESOURCES.REPORT]: [ACTIONS.READ],
    [RESOURCES.SETTINGS]: [ACTIONS.READ],
    [RESOURCES.AUDIT_LOG]: [],
    [RESOURCES.SUBSCRIPTION]: [],
    [RESOURCES.NOTIFICATION]: [ACTIONS.READ],
    [RESOURCES.TELEMEDICINE]: [],
    [RESOURCES.QUEUE]: [ACTIONS.READ],
    [RESOURCES.IMAGING_STUDY]: [ACTIONS.READ],
    [RESOURCES.REFERRAL]: [ACTIONS.READ],
    [RESOURCES.INSURANCE_CLAIM]: [ACTIONS.READ],
    [RESOURCES.PROCEDURE]: [ACTIONS.READ],
    [RESOURCES.CARE_PLAN]: [ACTIONS.READ],
    [RESOURCES.TASK]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.CONSENT]: [ACTIONS.READ],
  },

  // Manager (CursorMD/New: view-only reports, add/edit patients basic, book appointments, create invoices no pricing, no medical records, no inventory manage, no staff, no settings)
  manager: {
    [RESOURCES.PATIENT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.APPOINTMENT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.CANCEL],
    [RESOURCES.PRESCRIPTION]: [],
    [RESOURCES.INVOICE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.PAYMENT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.LAB_TEST]: [ACTIONS.READ],
    [RESOURCES.LAB_ORDER]: [ACTIONS.READ],
    [RESOURCES.LAB_RESULT]: [ACTIONS.READ],
    [RESOURCES.CLINICAL_NOTE]: [],
    [RESOURCES.INVENTORY]: [ACTIONS.READ],
    [RESOURCES.USER]: [],
    [RESOURCES.DOCTOR]: [ACTIONS.READ],
    [RESOURCES.DEPARTMENT]: [ACTIONS.READ],
    [RESOURCES.REPORT]: [ACTIONS.READ],
    [RESOURCES.SETTINGS]: [],
    [RESOURCES.AUDIT_LOG]: [],
    [RESOURCES.SUBSCRIPTION]: [],
    [RESOURCES.NOTIFICATION]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.TELEMEDICINE]: [],
    [RESOURCES.QUEUE]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.IMAGING_STUDY]: [ACTIONS.READ],
    [RESOURCES.REFERRAL]: [ACTIONS.READ],
    [RESOURCES.INSURANCE_CLAIM]: [ACTIONS.READ],
    [RESOURCES.PROCEDURE]: [ACTIONS.READ],
    [RESOURCES.CARE_PLAN]: [ACTIONS.READ],
    [RESOURCES.TASK]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.CONSENT]: [ACTIONS.READ],
  },
};

/** CursorMD/New: clinic_admin in DB maps to Admin role in spec. Normalize to lowercase for permission lookup. */
export function resolveRole(role) {
  if (!role) return '';
  if (role === 'clinic_admin') return 'admin';
  return String(role).toLowerCase();
}

/**
 * Check if a role has permission for a resource and action
 */
export function hasPermission(role, resource, action) {
  const r = resolveRole(role);
  if (!PERMISSIONS[r]) {
    return false;
  }

  const rolePermissions = PERMISSIONS[r];
  if (!rolePermissions[resource]) {
    return false;
  }

  const allowedActions = rolePermissions[resource];

  // MANAGE permission grants all actions
  if (allowedActions.includes(ACTIONS.MANAGE)) {
    return true;
  }

  return allowedActions.includes(action);
}

/**
 * Get all permissions for a role
 */
export function getRolePermissions(role) {
  return PERMISSIONS[resolveRole(role)] || {};
}

/**
 * Get all roles that have permission for a resource and action
 */
export function getRolesWithPermission(resource, action) {
  const roles = [];
  for (const [role, permissions] of Object.entries(PERMISSIONS)) {
    if (hasPermission(role, resource, action)) {
      roles.push(role);
    }
  }
  return roles;
}
