/** @type {import('tailwindcss').Config} – match clinic tool theme 100% */
module.exports = {
  darkMode: 'class',
  content: ['./app/**/*.{js,jsx}', './components/**/*.{js,jsx}'],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: '16px',
        sm: '20px',
        lg: '24px',
        xl: '28px',
        '2xl': '32px',
      },
    },
    extend: {
      colors: {
        primary: {
          900: 'var(--color-primary-900)',
          700: 'var(--color-primary-700)',
          600: 'var(--color-primary-600)',
          500: 'var(--color-primary-500)',
          300: 'var(--color-primary-300)',
          200: 'var(--color-primary-200)',
          100: 'var(--color-primary-100)',
          50: 'var(--color-primary-50)',
        },
        secondary: {
          700: 'var(--color-secondary-700)',
          600: 'var(--color-secondary-600)',
          500: 'var(--color-secondary-500)',
          300: 'var(--color-secondary-300)',
          100: 'var(--color-secondary-100)',
        },
        neutral: {
          900: 'var(--color-neutral-900)',
          800: 'var(--color-neutral-800)',
          700: 'var(--color-neutral-700)',
          600: 'var(--color-neutral-600)',
          500: 'var(--color-neutral-500)',
          300: 'var(--color-neutral-300)',
          200: 'var(--color-neutral-200)',
          100: 'var(--color-neutral-100)',
          50: 'var(--color-neutral-50)',
        },
        status: {
          success: 'var(--color-status-success)',
          warning: 'var(--color-status-warning)',
          error: 'var(--color-status-error)',
          info: 'var(--color-status-info)',
        },
        success: {
          700: 'var(--color-success-700)',
          600: 'var(--color-success-600)',
          500: 'var(--color-success-500)',
          300: 'var(--color-success-300)',
          100: 'var(--color-success-100)',
        },
        cta: {
          primary: 'var(--color-cta-primary)',
          'primary-hover': 'var(--color-cta-primary-hover)',
        },
      },
      fontFamily: {
        sans: [
          'var(--font-family)',
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          'Roboto',
          'Segoe UI',
          'Helvetica Neue',
          'Arial',
          'sans-serif',
        ],
        mono: ['var(--font-mono)', 'JetBrains Mono', 'Roboto Mono', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        h1: ['32px', { lineHeight: '40px', fontWeight: '700' }],
        h2: ['24px', { lineHeight: '32px', fontWeight: '600' }],
        h3: ['20px', { lineHeight: '28px', fontWeight: '600' }],
        h4: ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '21px', fontWeight: '400' }],
        'body-xs': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        button: ['16px', { lineHeight: '20px', fontWeight: '600' }],
        'metric-lg': ['24px', { lineHeight: '1.25', fontWeight: '600' }],
        'metric-md': ['20px', { lineHeight: '1.3', fontWeight: '600' }],
        'metric-sm': ['18px', { lineHeight: '1.35', fontWeight: '600' }],
      },
      spacing: {
        4: '4px',
        8: '8px',
        12: '12px',
        16: '16px',
        24: '24px',
        32: '32px',
        40: '40px',
        48: '48px',
        56: '56px',
        64: '64px',
        'icon-text': 'var(--icon-text-gap)',
      },
      borderRadius: {
        none: '0',
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius-lg)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        focus: '0 0 0 3px rgba(18,57,146,0.20)',
      },
    },
  },
  plugins: [],
};
